@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzE5ZjcyYTg1YWI1MDQ3ZTcyYTNlYiIsImlhdCI6MTcwMjYzNjY0MSwiZXhwIjoxNzEwNDEyNjQxfQ.d-i-YfukCQrGvh7JAj8FtXnAgH-YyuK0i0_2tPy4pcg
###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com", 
  "password": "admin"
}

###
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@example.com",
  "password": "admin",
  "role": "admin" 
}



###
# Create a new user
POST http://localhost:3000/api/v1/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "newUser6",
    "email": "newuse6r@example.com",
    "password": "password123",
    "role": "user"
}
###

###
# Get a specific user
GET http://localhost:3000/api/v1/users/{userId}
Authorization: Bearer {{token}}
Content-Type: application/json


###
# Update a specific user
PATCH http://localhost:3000/api/v1/users/{userId}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "updatedUser",
    "email": "updateduser@example.com"
}


###
# Delete a specific user
DELETE http://localhost:3000/api/v1/users/{userId}
Authorization: Bearer {{token}}
Content-Type: application/json


###
# list all users
GET http://localhost:3000/api/v1/users/
Authorization: Bearer {{token}}
Content-Type: application/json