

###
GET  http://localhost:3000/api/v1/ingredients
Content-Type: application/json

###
GET  http://localhost:3000/api/v1/ingredients/ingredient/65a813dd979d884761a25c3b
Content-Type: application/json

###
POST http://localhost:3000/api/v1/ingredients/ingredient
Content-Type: application/json

{
  "nom": "Farine de blé T55",
  "quantite": 100,
  "nutritionInfo": {
    "calories": 50,
    "protein": 50,
    "fat": 1
  }
}


###
# Mettre à jour un ingrédient spécifique
PATCH http://localhost:3000/api/v1/ingredients/ingredient/65a81be9e27fbfa7513f9798
Content-Type: application/json

{
  "name": "Farine de blé mise à jour",
  "quantite": 100,
  "nutritionInfo": {
    "calories": 350,
    "protein": 11,
    "fat": 0.8
  }
}


###
# Supprimer un ingrédient spécifique
DELETE http://localhost:3000/api/v1/ingredients/ingredient/65a82069f63db3640ec2865c
Content-Type: application/json


