
###
GET  http://localhost:3000/api/v1/recipes
Content-Type: application/json

###
GET  http://localhost:3000/api/v1/recipes/recipe/6573207411605f7f3dcf28be
Content-Type: application/json

###
POST http://localhost:3000/api/v1/recipes/recipe
Content-Type: application/json

{
  "title": "Gâteau au Kaki",
  "description": "Un délicieux gâteau au Kaki étrange et riche.",
   "ingredients": [
    {
      "ingredient": "6573158a027ed738bd0e1010",
      "quantity": "200g"
    },
      {
      "ingredient": "6573158a027ed738bd0e1010",
      "quantity": "200g"
    }
  ],
  "steps": [
    "Préchauffer le four à 180°C.",
    "Faire fondre le Kaki et le beurre.",
    "Ajouter le sucre et les œufs, puis incorporer la farine.",
    "Verser la pâte dans un moule et cuire pendant 25 minutes."
  ],
  "prepTime": 60,
  "images": [
    "url_image_gateau_chocolat.jpg"
  ],
  "comments": [
    {
    "user": "65719f72a85ab5047e72a3eb",
    "text": "Meilleur gâteau au Kaki de la planète !",
    "rating": 5,
    "createdAt": "2023-12-06T00:00:00.000Z"
    }, 
    {
    "user": "65719f72a85ab5047e72a3eb",
    "text": "Meilleur gâteau que j'ai jamais fait !",
    "rating": 5,
    "createdAt": "2023-12-06T00:00:00.000Z"
    }
  ],
  "category":  [ "dessert", "fruit" ]
}


###
POST http://localhost:3000/api/v1/recipes/recipe
Content-Type: application/json

{
  "title": "Gâteau au chocolat swizz",
  "description": "Un délicieux gâteau au chocolat moelleux et riche.",
  "ingredients": [
    {
      "name": "Chocolat",
      "marque": "swizzmax",
      "quantity": "200g"
    },
    {
      "name": "Beurre",
      "quantity": "100g"
    },
    {
      "name": "Sucre",
      "quantity": "150g"
    },
    {
      "name": "Oeufs",
      "quantity": "3"
    },
    {
      "name": "Farine",
      "quantity": "200g"
    }
    // Ajoutez d'autres ingrédients ici si nécessaire
  ],
  "steps": [
    "Préchauffer le four à 180°C.",
    "Faire fondre le chocolat et le beurre.",
    "Ajouter le sucre et les œufs, puis incorporer la farine.",
    "Verser la pâte dans un moule et cuire pendant 25 minutes."
  ],
  "prepTime": 60,
  "images": [
    "url_image_gateau_chocolat.jpg"
  ],
  "comments": {
    "user": "65719f72a85ab5047e72a3eb",
    "text": "Meilleur gâteau au chocolat que j'ai jamais fait !",
    "rating": 5,
    "createdAt": "2023-12-06T00:00:00.000Z"
  },
  "category": "dessert"
}
